"""first migration

Revision ID: 042b4a2d50c2
Revises: 
Create Date: 2021-01-30 08:42:14.122655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042b4a2d50c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('cat_link', sa.String(length=512), nullable=True),
    sa.Column('shop', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_category_id'), 'scraper_category', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_scraper_category_id'), table_name='scraper_category')
    op.drop_table('scraper_category')
    # ### end Alembic commands ###
