"""removed services tables

Revision ID: 4231210fe803
Revises: bf239cbb6f32
Create Date: 2021-04-05 17:54:23.733107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4231210fe803'
down_revision = 'bf239cbb6f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plastic_services_id', table_name='plastic_services')
    op.drop_table('plastic_services')
    op.drop_index('ix_beauty_services_id', table_name='beauty_services')
    op.drop_table('beauty_services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beauty_services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service', sa.VARCHAR(length=512), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1512), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('host_service_name', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_beauty_services_id', 'beauty_services', ['id'], unique=False)
    op.create_table('plastic_services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service', sa.VARCHAR(length=512), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1512), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('host_service_name', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plastic_services_id', 'plastic_services', ['id'], unique=False)
    # ### end Alembic commands ###
