"""removed refcodes table

Revision ID: 45b5a2d6cda9
Revises: ecdc1a06d6ea
Create Date: 2021-06-08 19:53:40.010145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b5a2d6cda9'
down_revision = 'ecdc1a06d6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ref_codes_id', table_name='ref_codes')
    op.drop_table('ref_codes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cat_link', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ref_codes_id', 'ref_codes', ['id'], unique=False)
    # ### end Alembic commands ###
