"""temp removed

Revision ID: 73d33d3103aa
Revises: ee54b54fdde2
Create Date: 2021-04-04 17:19:24.280041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d33d3103aa'
down_revision = 'ee54b54fdde2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plastic_services_id', table_name='plastic_services')
    op.drop_table('plastic_services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plastic_services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service', sa.VARCHAR(length=512), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('host_service_name', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plastic_services_id', 'plastic_services', ['id'], unique=False)
    # ### end Alembic commands ###
