"""removes salons tables

Revision ID: 91f8e69bc6e0
Revises: 176aef0a6c69
Create Date: 2021-05-10 07:40:32.271891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f8e69bc6e0'
down_revision = '176aef0a6c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_beauty_services_id', table_name='beauty_services')
    op.drop_table('beauty_services')
    op.drop_index('ix_plastic_services_id', table_name='plastic_services')
    op.drop_table('plastic_services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plastic_services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service', sa.VARCHAR(length=512), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1512), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('old_name', sa.VARCHAR(length=1512), nullable=True),
    sa.Column('host_service_name', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plastic_services_id', 'plastic_services', ['id'], unique=False)
    op.create_table('beauty_services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service', sa.VARCHAR(length=512), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1512), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('old_name', sa.VARCHAR(length=1512), nullable=True),
    sa.Column('host_service_name', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_beauty_services_id', 'beauty_services', ['id'], unique=False)
    # ### end Alembic commands ###
