"""description cell for plastic services

Revision ID: c6a561697f7a
Revises: 73d33d3103aa
Create Date: 2021-04-04 17:21:11.744648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a561697f7a'
down_revision = '73d33d3103aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plastic_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=1512), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('host_service_name', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plastic_services_id'), 'plastic_services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plastic_services_id'), table_name='plastic_services')
    op.drop_table('plastic_services')
    # ### end Alembic commands ###
