"""RefCodes table

Revision ID: ecdc1a06d6ea
Revises: 91f8e69bc6e0
Create Date: 2021-06-07 17:53:57.948057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdc1a06d6ea'
down_revision = '91f8e69bc6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_link', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_codes_id'), 'ref_codes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ref_codes_id'), table_name='ref_codes')
    op.drop_table('ref_codes')
    # ### end Alembic commands ###
